### ISSUE TITLE
Clarify the use of ComplianceChecker and FMPy

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-cross-check#100]

**Comment by lochel** [comment]
What is this issue about? Please provide a description.

**Comment by beutlich** [comment]
@andreas-junghanns Was it clarified then or closed w/o clarification?

**Comment by andreas-junghanns** [comment]
Closed w/o clarification: This is a non-issue right now. The ComplianceChecker cannot check 3.0 FMUs, only FMPy can.
Such is a power of the factual.
