### ISSUE TITLE
Retroactively flagging FMUs as non-compliant

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [modelica/fmi-cross-check#104]
Should this be allowed?  If an FMU passed validation using an FMPy version available at the time of check-in, it should be listed as compliant.  It seems not logical to expect past FMUs to comply with future releases of verification tools.  
A MapleSim 2018 and 2019 FMU was flagged as not compliant recently.  While the problem is valid (modelDescription
contains an error but the FMU still runs as expected), it was not detected by FMPy version available at the time of submission.

**Comment by chrbertsch** [comment]
IMHO "compliance" should be w.r.t the FMI standard and not w.r.t. a validation tool.
If the other way round the FMU would be valid according to the standard by fail the validation tool check, you would not accept this, but insist on fixing the tool.
Thus I think everything is ok and propose to close this issue.

**Comment by Maplesoft-fmigroup** [comment]
Ideally yes, the FMUs should be compliant wrt the standard.  But how do you check?  
Also, it seems odd to label FMUs that were deemed valid for couple of years as non-compliant all of a sudden.

**Comment by lochel** [comment]
If a FMU is actually not compliant with the FMI standard then it must be labeled as such. I guess we all can agree on that at least. It is unfortunate if it gets discovered later on but, never the less, one cannot expect other tools to support such a non-compliant FMU. Therefore, it must be flagged as non-compliant - even retroactively.
