### ISSUE TITLE
No working CI / master failing

### ISSUE THREAD

**Issue by AnHeuermann** [modelica/fmi-cross-check#107]
The CirclecCI was disabled with commit https://github.com/modelica/fmi-cross-check/commit/c06c9b4a068b640edd210c544a9419163367e13c. 

Will there be a new continuous integration to validate the master branch and PRs?

When running `python -m fmpy.cross_check.validate_vendor_repo` on the master branch I get a giant load of error messages. So it would be very important to have at least a rudimentary CI for the moment until a proper one can be set up to keep the master branch error free.

**Comment by t-sommer** [comment]
Please run `validate_repo.py` locally before opening a PR. The docs have not yet been updated to reflect this change.

**Comment by AnHeuermann** [comment]
Ah okay. I'll do that as soon as the script is finished or the documentation is updated.

We plan to add OMSimulator and OpenModelica to the FMI Cross Check and for that would run parts or all of this repo on our Jenkins machines. But in my opinion the `validate_repo.py` script needs to be improved. It is incredible slow, because it is only running on a single thread on a machine with many threads available.

Also I think it would be a good idea to add some more basic options and checks to `validate_repo.py`, e.g. only check parts of the repo. There is no need to run the validation on the whole repo, when I only add one specific version of one tool.
Also a check if all files that are needed as displayed in https://github.com/modelica/fmi-cross-check#add-fmus and only those are present. I forgot to add the `passed`/`failed` files in https://github.com/modelica/fmi-cross-check/pull/106 and you found it (by looking on it?), but a PR should automatically be checked for that.

**Comment by t-sommer** [comment]
The CI is currently disabled due to technical issues. Please open a PR if you want to make changes to `validate_repo.py`.

**Comment by lochel** [comment]
@t-sommer which issue is dealing with the technical issues?
