### ISSUE TITLE
fmus/2.0/cs/c-code/MapleSim/2018/Rectifier has the wrong FMI version

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-cross-check#11]
https://github.com/modelica/fmi-cross-check/blob/master/fmus/2.0/cs/c-code/MapleSim/2018/Rectifier/Rectifier.fmu is actually an FMI 1.0 FMU.

**Comment by t-sommer** [comment]
@Maplesoft-fmigroup, can you update the file?

**Comment by Maplesoft-fmigroup** [comment]
Updated c-code fmus in pull request: [https://github.com/modelica/fmi-cross-check/pull/16](url)

**Comment by t-sommer** [comment]
The branch cannot be merged. Can you resolve the conflicts?

**Comment by Maplesoft-fmigroup** [comment]
Fixed in https://github.com/modelica/fmi-cross-check/pull/16.
