### ISSUE TITLE
no LICENSE.txt for this repository

### ISSUE THREAD

**Issue by ForrestTrepte** [modelica/fmi-cross-check#114]
This repository doesn't seem to have a [license file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#:~:text=You%20can%20include%20an%20open,for%20other%20people%20to%20contribute.). This makes it difficult and unclear for others to freely use, change, or distribute the project.

Would it be possible to add a LICENSE.TXT. Something permissive like MIT License would be great!

**Comment by chrbertsch** [comment]
This is a good point.
However, as source code FMUs will contain proprietary code from the tool vendor, it will not be possible to put the whole repo under an open source license.
What we would need is something like an "all rights reserved by the exporting tool vendors, usage of the uploaded FMUs only for testing" license. Does someone know a standard license text for such a purpose.
And perhaps an license text in the tool-individual subfolders. Additionally tool vendors have to comply with licenses of open source tools used in the creation of their FMUs. Such licenses should be added to the documentation folder of an FMU.

**Comment by ForrestTrepte** [comment]
Ah, I think I see the problem. So the individual FMUs may contain proprietary things that the vendors don't want to provide under a permissive open-source license? But you do want to give users of fmi-cross-check permission to use those FMUs for testing compatibility.

For users of this repository, it would be helpful to explain how that works and have it all covered in a LICENSE.TXT. But I'm not sure exactly how that should be structured.

**Comment by ForrestTrepte** [comment]
@chrbertsch, I don't know of standard open-source license that is "for testing only". Although it would be nice to have a default LICENSE.txt that applies to the repository, I have alternative suggestion for you to consider:

Instead, you could add a statement to the readme describing what is permitted. Perhaps add a section to the readme about how to run the tests and state that the contents of the repository may be freely used for the purpose of testing compatibility with the FMI standard. That way you don't need a special legal agreement, but the repository explicitly states how it can be used for its intended purpose.

**Comment by andreas-junghanns** [comment]
> However, as source code FMUs will contain proprietary code from the tool vendor, it will not be possible to put the whole repo under an open source license.
> What we would need is something like an "all rights reserved by the exporting tool vendors, usage of the uploaded FMUs only for testing" license. Does someone know a standard license text for such a purpose.
> And perhaps an license text in the tool-individual subfolders. Additionally tool vendors have to comply with licenses of open source tools used in the creation of their FMUs. Such licenses should be added to the documentation folder of an FMU.

@chrbertsch : Agreed with your second sentence above. Let´s do that. The readme should also state your third sentence: "We expect tool vendors to comply and publish to all licenses used in the creation of the FMUs they release in this repository.".
Sad we have to state it, but let´s make sure no misunderstandings happen.

**Comment by ForrestTrepte** [comment]
@andreas-junghanns: Would this make it clear that users are permitted to execute all the tests for verifying compatibility with the FMI standard? Or would such users need to study separate licenses provided by the tool vendors for each individual test?

**Comment by andreas-junghanns** [comment]
> 
> 
> @andreas-junghanns: Would this make it clear that users are permitted to execute all the tests for verifying compatibility with the FMI standard? Or would such users need to study separate licenses provided by the tool vendors for each individual test?

To be safe we should say that, but that should go without saying, even if we would expect vendors not to restruct use reasonable. In general, the XC rules state that what you upload must be freely licensed for XC purposes, at least. Maybe we should refer to the XC rules as well?

**Comment by ForrestTrepte** [comment]
@andreas-junghanns: It would be nice to explicitly state that. In skimming the readme and FMI Cross-Check rules, I didn't see anything about how the tests can be used.

**Comment by pamagister** [comment]
It would be great having a LICENSE.txt coming with each FMU, zipped into the FMU/Documentation-folder like here in this BouncingBall.fmu (see link below). This way, you will have a self-contained license that will allow redistribution of the FMU, e.g. if the FMU is used for own cross-check purposes.

https://github.com/modelica/fmi-cross-check/blob/master/fmus/2.0/cs/win64/Test-FMUs/0.0.2/BouncingBall/BouncingBall.fmu
