### ISSUE TITLE
solidThinking_Activate/2020/CVloop/ doesn't comply with the rules for the directory structure

### ISSUE THREAD

**Issue by lochel** [modelica/fmi-cross-check#127]
The example `solidThinking_Activate/2020/CVloop/` doesn't comply with the rules for the directory structure.

There is a typo in the FMU name CVLoop.fmu, which should be CVloop.fmu.
> fmus/2.0/me/linux64/solidThinking_Activate/2020/CVloop/CVloop.fmu does not exist

_Originally posted by @lochel in https://github.com/modelica/fmi-cross-check/issues/110#issuecomment-880672688_

**Comment by masoud-najafi** [comment]
Should I rename all CVLoop.* files to CVloop.* by adding CVloop., then removing CVLoop. ?

**Comment by lochel** [comment]
I am a bit afraid that it might cause problems on Windows but honestly I don't know.

**Comment by t-sommer** [comment]
You can change the capitalization in git (see https://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git).

**Comment by masoud-najafi** [comment]
Thanks Torsten.
I made the  PR https://github.com/modelica/fmi-cross-check/pull/131 for renaming the files.

**Comment by lochel** [comment]
PR #131 was merged and that solves this problem. Thanks @masoud-najafi.
