### ISSUE TITLE
Cross-check should verify derivative attribute

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [modelica/fmi-cross-check#24]
On page 54 of FMI2.0 spec it says:
> The state derivatives of an FMU are listed under element <ModelStructure><Derivatives>. All ScalarVariables listed in this element must have attribute derivative (in order that the continuous-time states are uniquely defined).

However, there are FMUs in the repository that fail to provide this information.  For example:
https://github.com/modelica/fmi-cross-check/blob/master/fmus/2.0/cs/win64/MWorks/2016/MixtureGases/MixtureGases.fmu

has four Derivatives declared in the ModelStructure but there are no ScalarVariables with the <derivative> attribute.  This makes the FMU invalid and thus it should not pass the cross checker.

**Comment by t-sommer** [comment]
The following FMUs do not define derivatives for all continuous state variables as required by the rule cited above:

```
/fmus/2.0/me/win64/MWorks/2016/fullRobot/fullRobot.fmu
/fmus/2.0/me/win64/MWorks/2016/CoupledClutches/CoupledClutches.fmu
/fmus/2.0/me/win64/MWorks/2016/Rectifier/Rectifier.fmu
/fmus/2.0/me/win64/MWorks/2016/MixtureGases/MixtureGases.fmu
/fmus/2.0/me/win64/MWorks/2016/ControlledTemperature/ControlledTemperature.fmu
/fmus/2.0/me/win64/MWorks/2016/BouncingBall/BouncingBall.fmu
/fmus/2.0/me/win64/Easy5/2017.1/PneumaticActuator/PneumaticActuator.fmu
/fmus/2.0/me/win64/Easy5/2017.1/Linear_Pos/Linear_Pos.fmu
/fmus/2.0/me/win64/Easy5/2017.1/VanDerPol/VanDerPol.fmu
/fmus/2.0/me/win32/MWorks/2016/fullRobot/fullRobot.fmu
/fmus/2.0/me/win32/MWorks/2016/CoupledClutches/CoupledClutches.fmu
/fmus/2.0/me/win32/MWorks/2016/Rectifier/Rectifier.fmu
/fmus/2.0/me/win32/MWorks/2016/MixtureGases/MixtureGases.fmu
/fmus/2.0/me/win32/MWorks/2016/ControlledTemperature/ControlledTemperature.fmu
/fmus/2.0/me/win32/MWorks/2016/BouncingBall/BouncingBall.fmu
```
