### ISSUE TITLE
Locals in FMU export reference files

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-cross-check#27]
**Reported by maplesoft on 30 Jan 2017 14:16 UTC**
A number of exported FMUs contain data for local variables in the reference files.  Since these local variables are internal to the FMU and are listed under 'protected' section during Import, the importing tools may not allow access to such variables including for the purposes of plotting.  We propose that the local variables should not be included in the reference CSV files, only outputs and states.

----

Migrated-From: https://trac.fmi-standard.org/ticket/408

**Comment by t-sommer** [comment]
Closed in favor of #35
