### ISSUE TITLE
AVL Cruise-M FMUs

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-cross-check#37]
Why does AVL-Cruise have the "greeen button" for FMU-export (e.g. FMU 2.0 CS)? I cannot find any uploaded FMUs or reference results for any platform. (CC:  @klausschuch) Thanks in advance for clarifying

**Comment by t-sommer** [comment]
AVL has no green button for FMU export for any of its tools:

![avl-cross-check](https://user-images.githubusercontent.com/2453858/53401132-7f575280-39af-11e9-8309-7a4d7ca9f4fd.PNG)

**Comment by chrbertsch** [comment]
Oh, I am sorry I misinterperted the columns.
