### ISSUE TITLE
Add missing FMUSDK FMUs

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-cross-check#48]
The FMUSDK is extremely valuable for testing different aspects of the FMI.
It would be great to have a complete set of pre-compiled FMUs for all platforms (at least for the latest release).

- missing FMUs: values.fmu (the only FMU to test String I/O)
- missing platforms: darwin64, linux32, linux64

**Comment by t-sommer** [comment]
@StefanOltean, can you look into this?

**Comment by chrbertsch** [comment]
Can this be closed? There are FMUSDK FMUs, e.g., https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/win64/FMUSDK
