### ISSUE TITLE
Problems running Test-FMUs

### ISSUE THREAD

**Issue by StefanOltean** [modelica/fmi-cross-check#54]
Hello,

I've faced some issues running some Test-FMUs in QTronic Silver. If this is not the correct place to raise these issues please let me know whom I should get in contact with. 

1. [2.0\cs\win64\Test-FMUs\0.0.01\Feedthrough](https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/win64/Test-FMUs/0.0.1/Feedthrough) - seems like this one is expecting some input signals (bool_in, int_in, real_continous_in, etc.) but these are not available as a .csv file.

2. [1.0\cs\win64\Test-FMUs\0.0.1\Resource](https://github.com/modelica/fmi-cross-check/tree/master/fmus/1.0/cs/win64/Test-FMUs/0.0.1/Resource) - when running this FMU in SIlver, it produces the following error message. The 2.0 version of this FMU works as expected. Could there be an issue with the 1.0 FMU?
`Resource: Resource (logError): Failed to open resource file C:\work\projects\12_FMI_XC\repos\fmi-cross-check-SO-branch\fmus\1.0\cs\win64\Test-FMUs\0.0.1\Resource\9L7YK_cs0_10232.`

3. [1.0\me\win64\Test-FMUs\0.0.1\Stair](https://github.com/modelica/fmi-cross-check/tree/master/fmus/1.0/me/win64/Test-FMUs/0.0.1/Stair) - the output of this FMU is constant throughout the simulation, there are no error message thrown by the FMU. The 2.0 version of this FMU works as expected. Could you please check if this behaves as it should? Have other tools reported issues with it?

Regards,
Stefan
QTronic GmbH

**Comment by t-sommer** [comment]
Thanks for your help, @StefanOltean. I will look into this.

**Comment by t-sommer** [comment]
> 2.0\cs\win64\Test-FMUs\0.0.01\Feedthrough - seems like this one is expecting some input signals (bool_in, int_in, real_continous_in, etc.) but these are not available as a .csv file.

I've added the missing input files.

> 1.0\cs\win64\Test-FMUs\0.0.1\Resource - when running this FMU in SIlver, it produces the following error message. The 2.0 version of this FMU works as expected. Could there be an issue with the 1.0 FMU?

> 1.0\me\win64\Test-FMUs\0.0.1\Stair - the output of this FMU is constant throughout the simulation, there are no error message thrown by the FMU. The 2.0 version of this FMU works as expected. Could you please check if this behaves as it should? Have other tools reported issues with it?

The two FMUs produce the expected output on my machine. Please open an issue on the [Test-FMUs repo](https://github.com/CATIA-Systems/test-fmus) if you've found a bug.
