### ISSUE TITLE
uploads to fmi-standard.org failed

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-cross-check#80]
The last two ci uploads failed with:
`[master 35b9440] Adding cross-check results from CI (build 245)
 2 files changed, 11 insertions(+), 9 deletions(-)
 rewrite _data/cross-check/result.csv (75%)
To github.com:modelica/fmi-standard.org.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:modelica/fmi-standard.org.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Exited with code exit status 1`

It seems that this happened before too.

**Comment by chrbertsch** [comment]
@klausschuch : please re-open if this still persists.

**Comment by t-sommer** [comment]
The CI is currently disabled.
