### ISSUE TITLE
Reference results of fmi-cross-check/fmus/2.0/me/win64/Test-FMUs/0.0.2/BouncingBall/

### ISSUE THREAD

**Issue by TorstenBlochwitz** [modelica/fmi-cross-check#86]
The reference results of the Co-Simulation FMU BouncingBall contains results with time values which are not monotonically increasing. This violates the FMI CrossCheck Rules (see Appendix B).

Could you please correct this? It is misleading for users.

I just noticed the same for the corresponding model exchange FMU and for the FMUs Stair and Feedthrough.

**Comment by t-sommer** [comment]
From https://github.com/modelica/fmi-cross-check/blob/master/FMI-CROSS-CHECK-RULES.md#10-appendix-b--csv-rules:

> The first column contains the time. The values in time must be monotonically increasing.

The values of `time` are not required to be _strictly_  monotonically increasing. Allowing multiple equal time values is very useful to provide variable values before and after events.
