### ISSUE TITLE
circle ci fails - ssh passphrase missing

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-cross-check#94]
The ci of cross-check fails currently.
This is the error shown in the ci output:
`Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
Enter passphrase for key '/home/circleci/.ssh/id_rsa': 
Too long with no output (exceeded 10m0s)
CircleCI received exit code 1`

**Comment by andreas-junghanns** [comment]
@t-sommer : can you fix this?

**Comment by klausschuch** [comment]
The actual reason for this problem is not the missing ssh passphrase.
The repostitory is currently just too big and the git operation takes too long `Too long with no output (exceeded 10m0s) CircleCI received exit code 1`.
Hence, the problem will be fixed as soon as the huge number of results files get removed after changing the xc rules (see #90).
