### ISSUE TITLE
What "system" libraries can be assumed for the Cross Check?

### ISSUE THREAD

**Issue by AnHeuermann** [modelica/fmi-cross-check#99]
OMSimualtor is running the FMI Cross Check (see [libraries.openmodelica.org](https://libraries.openmodelica.org/fmi-crosschecking/OMSimulator/)) inside a Docker image with only a few libraries installed.
In this Docker images ( anheuermann/ompython on DockerHub: [Ubuntu Bionic](https://hub.docker.com/layers/anheuermann/ompython/bionic/images/sha256-54d62b0117f54e041141046570ad7a36edb869f552d504020f016809153c641d?context=repo), [Ubuntu Focal](https://hub.docker.com/layers/anheuermann/ompython/focal/images/sha256-81b9568a41cac8932dfd45ecb115f6f9a2857795ce9aff0ae4f625b77a26cc37?context=repo), [Ubuntu Bionic with Wine](https://hub.docker.com/layers/anheuermann/ompython/wine-bionic/images/sha256-1ef0229b11094dac34db7928c60fb9629e8c8b1e02660e19a8b07eb71774f0ab?context=repo) )  some libraries used by a lot of FMUs are not installed.

For example FMUs that use
  - libgfortran.so.3 ( Example: [ControlledTemperature from JModelica](https://libraries.openmodelica.org/fmi-crosschecking/OMSimulator/history/build-v2.1.0-232%202020-10-22/linux64-bionic/files/20.me.JModelica_org.1_15.ControlledTemperature/20.me.JModelica_org.1_15.ControlledTemperature.log.html) )
  - libpython3.7m.so ( Example [european_lv from pandapower](https://libraries.openmodelica.org/fmi-crosschecking/OMSimulator/history/build-v2.1.0-232%202020-10-22/linux64-focal/files/20.cs.pandapower.2_1_0.european_lv/20.cs.pandapower.2_1_0.european_lv.log.html) )
will always fail.

Which of these libraries are assumed every user of an FMU has locally installed? If I understand the FMI standard correctly every FMU should contain all libraries needed to run it, but that's not really realistic.
Adding the correct Fortran library for every linux64 system could be very hard.
But on the other hand it is not possible (or very hard) to install libgfortran.so.3 on Ubuntu Focal.

So my question:
Are the example FMUs not compliant with the latest rules of the FMI Cross Check or should I add the missing libraries to my Docker images?

**Comment by AnHeuermann** [comment]
Related issue: #57

**Comment by t-sommer** [comment]
FMUs with external dependencies are perfectly fine (e.g. a license server) but you'll have to accept the fact that very few people will be able (and willing) to simulate them.
